config/routes.rb
Rails.application.routes.draw do
  resources :advertisements
  resources :contacts ,only:[:new,:create] do
  	collection do
  		post :get_state
  		post :get_city
  	end
  end
  root 'posts#index'

  resources :posts
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/advertisement.rb
class Advertisement < ApplicationRecord
	mount_uploader :image ,ImageUploader
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  mount_uploader :image ,ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :posts
end

app/controllers/advertisements_controller.rb
class AdvertisementsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_advertisement, only: [:show, :edit, :update, :destroy]

  def new
    @advertisement = Advertisement.new
  end


  def edit
  end

  def create
    @advertisement = Advertisement.new(advertisement_params)

    respond_to do |format|
      if @advertisement.save
        format.html { redirect_to root_path, notice: 'Advertisement was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @advertisement.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @advertisement.update(advertisement_params)
        format.html { redirect_to root_path, notice: 'Advertisement was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @advertisement.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Advertisement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_advertisement
      @advertisement = Advertisement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def advertisement_params
      params.require(:advertisement).permit(:image, :title,:is_visible)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  # skip_before_action :verify_authenticity_token 
  
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to root_path, notice: 'Contact was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def get_state
    if params[:country].present?
       state = CS.states(params[:country].to_sym).map{|x| [x[0],x[1]]}
       render json: {"data" => state}
    end     
  end
  def get_city
    if params[:state].present?
       city = CS.cities(params[:state].to_sym)
       render json: {"data" => city}
    end     
  end

  private
   
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :country, :state, :city, :subject)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! 
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order(updated_at: :desc)
    @advertsiments = Advertisement.where(is_visible: true)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :description, :image, :user_id)
    end
end

app/helpers/advertisements_helper.rb
module AdvertisementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/advertisements/_form.html.erb
<div id="respond">
<h3>New Advertsiment</h3>
 <%= form_with(model: advertisement, local: true) do |form| %>
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <%= form.text_field :title, id: :advertisement_title,class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Image</label>
    <%= form.file_field :image, id: :advertisement_image %>
  </div>

  <div class="form-group">
    <label for="exampleInputFile">Is visible</label>
    <%= form.check_box :is_visible, id: :advertisement_is_visible %>
  </div>


  <%= form.submit "submit" ,class: "btn btn-default" %>
    <button type="Reset" class="btn btn-default">Reset</button>
  <%end%>
</div>    


   <style type="text/css">
     #respond{
      margin: 5% !important;
     }
   </style>

app/views/advertisements/edit.html.erb
<h1>&nbsp;</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Show', @advertisement %> |
<%= link_to 'Back', advertisements_path %>

app/views/advertisements/new.html.erb
<h1>&nbsp;</h1>

<%= render 'form', advertisement: @advertisement %>

<%= link_to 'Back', advertisements_path %>

app/views/contacts/_form.html.erb
<div id="respond">
<h3>Contact Us</h3>
  <%= form_with(model: contact, local: true) do |form| %>
  <div class="form-group">
    <label for="exampleInputEmail1">First name</label>
    <%= form.text_field :first_name, id: :contact_first_name,class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Last Name</label>
    <%= form.text_field :last_name, id: :contact_last_name,class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">Email</label>
     <%= form.text_field :email, id: :contact_email,class: "form-control" %>
  </div>


   <div class="form-group">
    <label for="exampleInputEmail1">Country</label>
     <%= form.select :country,  options_for_select(CS.countries.map{|x| [x[1],x[0]] }), {  },:class => 'form-control',id: :contact_country%>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">State</label>
    <%= form.select :state,options_for_select(""),{}, id: :contact_state ,class: "form-control"%>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">City</label>
      <%= form.select :city,options_for_select(""),{}, id: :contact_city ,class: "form-control"%>
  </div>


  <%= form.submit "submit" ,class: "btn btn-default" %>
    <button type="Reset" class="btn btn-default">Reset</button>
  <%end%>
</div> 
    
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

   <style type="text/css">
     #respond{
      margin: 5% !important;
     }
   </style>

<script type="text/javascript">
$("#contact_country").change(function(){
   set_state()
});
$("#contact_state").change(function(){
   set_city()
});
     function  set_state() {
        $.ajax({
            type: "POST",
            url: "/contacts/get_state",
            dataType: "json",
            data: {
                country: $("#contact_country").val(),
             
                'authenticity_token': '<%=form_authenticity_token %>'
            },
            success: function (result) {
               state = $("#contact_state");
               
              if (result.data.length > 0) { 
                    state.html("");
                    $("#contact_city").html("");
              for (var i = 0; i < result.data.length; i++) {  
                        state.append('<option value=' + result.data[i][0] + '>' + result.data[i][1] + '</option>');
                    }

                }
                else {
                    state.html('');
                }                
            }
        });
    }
    

       function  set_city() {
        $.ajax({
            type: "POST",
            url: "/contacts/get_city",
            dataType: "json",
            data: {
                state: $("#contact_state").val(),             
                'authenticity_token': '<%=form_authenticity_token %>'
            },
            success: function (result) {
               console.log(result)  
               manish = result;
               city = $("#contact_city");
               
              if (result.data.length > 0) { 
                    city.html("");
              for (var i = 0; i < result.data.length; i++) {  
                        city.append('<option value=' + result.data[i] + '>' + result.data[i] + '</option>');
                    }

                }
                else {
                    city.html('');
                }                
            }
        });
    }

</script>

app/views/contacts/new.html.erb
<h1>&nbsp;</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%=link_to image_tag('/assets/Logo1.png',width: "50" ,height: "50")%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">      
      
      <ul class="nav navbar-nav navbar-right">
      
        <li><a href="/">Home</a></li>
        <li> <%=link_to "New Post",new_post_path%></li>
         <li> <%=link_to "Contact Us",new_contact_path%></li>
        <%if current_user%>
        <li class="last"><%=link_to "Logout",destroy_user_session_path,method: :delete%></li>
        <%else%>
        <li><%=link_to "Registration",new_user_registration_path%></li>
         <li><%=link_to "Login",user_session_path%></li>
        <%end%>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoSite</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

     <!-- <script src="/assets/jquery.js"></script> -->
       <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
 
  </head>
  <%=render 'layouts/header'%>
    <%= yield %>
    </div>

<div class="wrapper col5">
  <div id="copyright">
    <p class="fl_left">Copyright &copy; 2017 - All Rights Reserved - <a href="#">Demo</a></p>
    <p class="fl_right">Develop & Design By Manish</a></p>
    <br class="clear" />
  </div>
</div>
  </body>
</html>

app/views/posts/_form.html.erb
<div id="respond">
<h3>New Post</h3>
  <%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <label for="exampleInputEmail1">Title</label>
    <%= form.text_field :title, id: :post_title,class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputPassword1">Description</label>
    <%= form.text_area :description, id: :post_description,class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="exampleInputFile">File input</label>
    <%= form.file_field :image, id: :post_image %>
  </div>


  <%= form.submit "submit" ,class: "btn btn-default" %>
    <button type="Reset" class="btn btn-default">Reset</button>
  <%end%>
</div> 
    
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

   <style type="text/css">
     #respond{
      margin: 5% !important;
     }
   </style>

app/views/posts/edit.html.erb
<h1>&nbsp;</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="wrapper col3">
  <div id="container">
    <div id="content">
    <%@posts.each do |post|%>  
    <!--   <img class="imgr" src="/assets/imgr.gif" alt="" width="125" height="125" />
      <p>Aliquatjusto quisque nam consequat doloreet vest orna partur scetur portortis nam. Metadipiscing eget facilis elit sagittis felisi eger id justo maurisus convallicitur.</p>
      <p>Dapiensociis <a href="#">temper donec auctortortis cumsan</a> et curabitur condis lorem loborttis leo. Ipsumcommodo libero nunc at in velis tincidunt pellentum tincidunt vel lorem.</p> -->
      <!-- <img class="imgl" src="/assets/imgl.gif" alt="" width="125" height="125" /> -->
       <h2><%=post.user.try(:email)%></h2>
       <%=link_to image_tag(post.try(:image).try(:url),width: "125" ,height: "125")%>
        <p><%=post.description%></p>
        <%=link_to "edit",edit_post_path(post)%>
         <%=link_to "Show",post_path(post)%>
      <%end%>
<!-- 
      <h2>Table(s)</h2>
      <table summary="Summary Here" cellpadding="0" cellspacing="0">
        <thead>
          <tr>
            <th>Header 1</th>
            <th>Header 2</th>
            <th>Header 3</th>
            <th>Header 4</th>
          </tr>
        </thead>
        <tbody>
          <tr class="light">
            <td>Value 1</td>
            <td>Value 2</td>
            <td>Value 3</td>
            <td>Value 4</td>
          </tr>
          <tr class="dark">
            <td>Value 5</td>
            <td>Value 6</td>
            <td>Value 7</td>
            <td>Value 8</td>
          </tr>
          <tr class="light">
            <td>Value 9</td>
            <td>Value 10</td>
            <td>Value 11</td>
            <td>Value 12</td>
          </tr>
          <tr class="dark">
            <td>Value 13</td>
            <td>Value 14</td>
            <td>Value 15</td>
            <td>Value 16</td>
          </tr>
        </tbody>
      </table> -->
      <!-- <div id="comments">
        <h2>Comments</h2>
        <ul class="commentlist">
          <li class="comment_odd">
            <div class="author"><img class="avatar" src="/assets/avatar.gif" width="32" height="32" alt="" /><span class="name"><a href="#">A Name</a></span> <span class="wrote">wrote:</span></div>
            <div class="submitdate"><a href="#">August 4, 2009 at 8:35 am</a></div>
            <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
          </li>
          <li class="comment_even">
            <div class="author"><img class="avatar" src="/assets/avatar.gif" width="32" height="32" alt="" /><span class="name"><a href="#">A Name</a></span> <span class="wrote">wrote:</span></div>
            <div class="submitdate"><a href="#">August 4, 2009 at 8:35 am</a></div>
            <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
          </li>
          <li class="comment_odd">
            <div class="author"><img class="avatar" src="/assets/avatar.gif" width="32" height="32" alt="" /><span class="name"><a href="#">A Name</a></span> <span class="wrote">wrote:</span></div>
            <div class="submitdate"><a href="#">August 4, 2009 at 8:35 am</a></div>
            <p>This is an example of a comment made on a post. You can either edit the comment, delete the comment or reply to the comment. Use this as a place to respond to the post or to share what you are thinking.</p>
          </li>
        </ul>
      </div>
      <h2>Write A Comment</h2>
      <div id="respond">
        <form action="#" method="post">
          <p>
            <input type="text" name="name" id="name" value="" size="22" />
            <label for="name"><small>Name (required)</small></label>
          </p>
          <p>
            <input type="text" name="email" id="email" value="" size="22" />
            <label for="email"><small>Mail (required)</small></label>
          </p>
          <p>
            <textarea name="comment" id="comment" cols="100%" rows="10"></textarea>
            <label for="comment" style="display:none;"><small>Comment (required)</small></label>
          </p>
          <p>
            <input name="submit" type="submit" id="submit" value="Submit Form" />
            &nbsp;
            <input name="reset" type="reset" id="reset" tabindex="5" value="Reset Form" />
          </p>
        </form>
      </div> -->
    </div>
    <div id="column">
      <div class="sponsors">
        <h2 class="title">Advertisiment</h2>
        <ul id="banner125">
        <%unless @advertsiments.present?%>
        <li><a href="javascript:void(0);"><img src="/assets/250x100.gif" alt="" width= "125" height=  "125" /></a></li>
        <%end%>
        <%@advertsiments.each do |advertsiment|%>
          <li><a href="javascript:void(0);"><img src="<%=advertsiment.image_url %>" alt="" width= "125" height=  "125"  /></a></li>
         <%end%>
        </ul>
        <div class="clear"></div>
      </div>      
    </div>
    <div class="clear"></div>
  </div>
</div>
</div>

app/views/posts/new.html.erb
<h1>&nbsp;</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="wrapper col3">
  <div id="container">
    <div id="respond">

    <!--   <img class="imgr" src="/assets/imgr.gif" alt="" width="125" height="125" />
      <p>Aliquatjusto quisque nam consequat doloreet vest orna partur scetur portortis nam. Metadipiscing eget facilis elit sagittis felisi eger id justo maurisus convallicitur.</p>
      <p>Dapiensociis <a href="#">temper donec auctortortis cumsan</a> et curabitur condis lorem loborttis leo. Ipsumcommodo libero nunc at in velis tincidunt pellentum tincidunt vel lorem.</p> -->
      <!-- <img class="imgl" src="/assets/imgl.gif" alt="" width="125" height="125" /> -->
       <h2><%=@post.user.try(:email)%></h2>
       <div><%=link_to image_tag(@post.try(:image).try(:url),width: "300" ,height: "300")%></div>
       <div class="set_inside"><p><%=@post.description%></p></div>
        <%=link_to "edit",edit_post_path(@post)%>
        <%= link_to 'Back', posts_path %>

    </div>
  </div>
</div>
 <style type="text/css">
     #respond{
      margin: 5% !important;
     }
   </style>